import type { Metadata } from "next";

import Navbar from "@/components/Navbar";

// Geist is initialised once in src/app/layout.tsx, which also applies the
// generated classes to <html>. Declaring the same fonts a second time here
// created two next/font instances competing over identical variable names,
// and neither layout applied `.variable` - so the app silently fell back to
// the browser default typeface.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}